---
- hosts: planet-express
  name: learning file manipulation

  tasks:
  - archive:
      path: /tmp/file1.txt
      dest: /tmp/file1.txt.gz

      #  - fetch:
      # src: /tmp/file1.txt
      # dest: /home/student/ansible/backup/

